name: Build and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build -- --configuration production --base-href /

      - name: Copy CNAME
        run: |
          if [ -f CNAME ]; then
            cp CNAME dist/SiteWebCabinetDentaire/browser/
          else
            echo "CNAME file not found, skipping copy."
          fi

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/SiteWebCabinetDentaire/browser
          branch: gh-pages
